# Generated by Django 2.1.5 on 2019-01-07 15:24

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grass',
            old_name='title',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grass',
            name='image',
            field=models.ImageField(upload_to=shop.models.image_folder),
        ),
    ]
